import type { Language } from "../types/core";

export const LANGUAGE_MAP = {
    MULTI: "multi",
    ARABIC: "ar",
    BELARUSIAN: "be",
    BENGALI: "bn",
    BULGARIAN: "bg",
    CHINESE: "zh",
    CHINESE_SIMPLIFIED: "zh-Hans",
    CHINESE_TRADITIONAL: "zh-Hant",
    CROATIAN: "hr",
    CZECH: "cs",
    DANISH: "da",
    DUTCH: "nl",
    ENGLISH: "en",
    ENGLISH_UK: "en-GB",
    ENGLISH_US: "en-US",
    ESTONIAN: "et",
    FILIPINO: "fil",
    FINNISH: "fi",
    FRENCH: "fr",
    FRENCH_CA: "fr-CA",
    GEORGIAN: "ka",
    GERMAN: "de",
    GREEK: "el",
    HINDI: "hi",
    HUNGARIAN: "hu",
    INDONESIAN: "id",
    IRISH: "ga",
    ITALIAN: "it",
    JAPANESE: "ja",
    KOREAN: "ko",
    LATVIAN: "lv",
    LITHUANIAN: "lt",
    MALAY: "ms",
    NEPALI: "ne",
    NORWEGIAN: "no",
    PERSIAN: "fa",
    POLISH: "pl",
    PORTUGUESE: "pt",
    PORTUGUESE_BR: "pt-BR",
    PORTUGUESE_PT: "pt-PT",
    ROMANIAN: "ro",
    RUSSIAN: "ru",
    SERBIAN: "sr",
    SINHALA: "si",
    SLOVAK: "sk",
    SLOVENIAN: "sl",
    SPANISH: "es",
    SPANISH_ES: "es-ES",
    SPANISH_LA: "es-419",
    SPANISH_MX: "es-MX",
    SWEDISH: "sv",
    TAMIL: "ta",
    TELUGU: "te",
    THAI: "th",
    TURKISH: "tr",
    UKRAINIAN: "uk",
    URDU: "ur",
    VIETNAMESE: "vi",
} as const;

export const LANGUAGES: Record<LANGUAGE_KEY, Language> = {
    multi: {
        key: "multi",
        name: "Multi-Language",
        flagCode: "🌍",
        iso6391: "",
    },
    ar: {
        key: "ar",
        name: "Arabic",
        flagCode: "🇸🇦",
        iso6391: "ar",
    },
    be: {
        key: "be",
        name: "Belarusian",
        flagCode: "🇧🇾",
        iso6391: "be",
    },
    bg: {
        key: "bg",
        name: "Bulgarian",
        flagCode: "🇧🇬",
        iso6391: "bg",
    },
    bn: {
        key: "bn",
        name: "Bengali",
        flagCode: "🇧🇩",
        iso6391: "bn",
    },
    cs: {
        key: "cs",
        name: "Czech",
        flagCode: "🇨🇿",
        iso6391: "cs",
    },
    da: {
        key: "da",
        name: "Danish",
        flagCode: "🇩🇰",
        iso6391: "da",
    },
    de: {
        key: "de",
        name: "German",
        flagCode: "🇩🇪",
        iso6391: "de",
    },
    ka: {
        key: "ka",
        name: "Georgian",
        flagCode: "🇬🇪",
        iso6391: "ka",
    },
    el: {
        key: "el",
        name: "Greek",
        flagCode: "🇬🇷",
        iso6391: "el",
    },
    en: {
        key: "en",
        name: "English",
        flagCode: "🇺🇸",
        iso6391: "en",
    },
    "en-GB": {
        key: "en-GB",
        name: "English (UK)",
        flagCode: "🇬🇧",
        iso6391: "en",
        region: "United Kingdom",
    },
    "en-US": {
        key: "en-US",
        name: "English (US)",
        flagCode: "🇺🇸",
        iso6391: "en",
        region: "United States",
    },
    es: {
        key: "es",
        name: "Spanish",
        flagCode: "🇪🇸",
        iso6391: "es",
    },
    "es-419": {
        key: "es-419",
        name: "Spanish (Latin America)",
        flagCode: "🌎",
        iso6391: "es",
        region: "Latin America",
    },
    "es-ES": {
        key: "es-ES",
        name: "Spanish (Spain)",
        flagCode: "🇪🇸",
        iso6391: "es",
        region: "Spain",
    },
    "es-MX": {
        key: "es-MX",
        name: "Spanish (Mexico)",
        flagCode: "🇲🇽",
        iso6391: "es",
        region: "Mexico",
    },
    et: {
        key: "et",
        name: "Estonian",
        flagCode: "🇪🇪",
        iso6391: "et",
    },
    fa: {
        key: "fa",
        name: "Persian",
        flagCode: "🇮🇷",
        iso6391: "fa",
    },
    fi: {
        key: "fi",
        name: "Finnish",
        flagCode: "🇫🇮",
        iso6391: "fi",
    },
    fil: {
        key: "fil",
        name: "Filipino",
        flagCode: "🇵🇭",
        iso6391: "fil",
    },
    fr: {
        key: "fr",
        name: "French",
        flagCode: "🇫🇷",
        iso6391: "fr",
    },
    "fr-CA": {
        key: "fr-CA",
        name: "French (Canada)",
        flagCode: "🇨🇦",
        iso6391: "fr",
        region: "Canada",
    },
    ga: {
        key: "ga",
        name: "Irish",
        flagCode: "🇮🇪",
        iso6391: "ga",
    },
    hi: {
        key: "hi",
        name: "Hindi",
        flagCode: "🇮🇳",
        iso6391: "hi",
    },
    hr: {
        key: "hr",
        name: "Croatian",
        flagCode: "🇭🇷",
        iso6391: "hr",
    },
    hu: {
        key: "hu",
        name: "Hungarian",
        flagCode: "🇭🇺",
        iso6391: "hu",
    },
    id: {
        key: "id",
        name: "Indonesian",
        flagCode: "🇮🇩",
        iso6391: "id",
    },
    it: {
        key: "it",
        name: "Italian",
        flagCode: "🇮🇹",
        iso6391: "it",
    },
    ja: {
        key: "ja",
        name: "Japanese",
        flagCode: "🇯🇵",
        iso6391: "ja",
    },
    ko: {
        key: "ko",
        name: "Korean",
        flagCode: "🇰🇷",
        iso6391: "ko",
    },
    lt: {
        key: "lt",
        name: "Lithuanian",
        flagCode: "🇱🇹",
        iso6391: "lt",
    },
    lv: {
        key: "lv",
        name: "Latvian",
        flagCode: "🇱🇻",
        iso6391: "lv",
    },
    ms: {
        key: "ms",
        name: "Malay",
        flagCode: "🇲🇾",
        iso6391: "ms",
    },
    ne: {
        key: "ne",
        name: "Nepali",
        flagCode: "🇳🇵",
        iso6391: "ne",
    },
    nl: {
        key: "nl",
        name: "Dutch",
        flagCode: "🇳🇱",
        iso6391: "nl",
    },
    no: {
        key: "no",
        name: "Norwegian",
        flagCode: "🇳🇴",
        iso6391: "no",
    },
    pl: {
        key: "pl",
        name: "Polish",
        flagCode: "🇵🇱",
        iso6391: "pl",
    },
    pt: {
        key: "pt",
        name: "Portuguese",
        flagCode: "🇵🇹",
        iso6391: "pt",
    },
    "pt-BR": {
        key: "pt-BR",
        name: "Portuguese (Brazil)",
        flagCode: "🇧🇷",
        iso6391: "pt",
        region: "Brazil",
    },
    "pt-PT": {
        key: "pt-PT",
        name: "Portuguese (Portugal)",
        flagCode: "🇵🇹",
        iso6391: "pt",
        region: "Portugal",
    },
    ro: {
        key: "ro",
        name: "Romanian",
        flagCode: "🇷🇴",
        iso6391: "ro",
    },
    ru: {
        key: "ru",
        name: "Russian",
        flagCode: "🇷🇺",
        iso6391: "ru",
    },
    si: {
        key: "si",
        name: "Sinhala",
        flagCode: "🇱🇰",
        iso6391: "si",
    },
    sk: {
        key: "sk",
        name: "Slovak",
        flagCode: "🇸🇰",
        iso6391: "sk",
    },
    sl: {
        key: "sl",
        name: "Slovenian",
        flagCode: "🇸🇮",
        iso6391: "sl",
    },
    sr: {
        key: "sr",
        name: "Serbian",
        flagCode: "🇷🇸",
        iso6391: "sr",
    },
    sv: {
        key: "sv",
        name: "Swedish",
        flagCode: "🇸🇪",
        iso6391: "sv",
    },
    ta: {
        key: "ta",
        name: "Tamil",
        flagCode: "🇮🇳",
        iso6391: "ta",
    },
    te: {
        key: "te",
        name: "Telugu",
        flagCode: "🇮🇳",
        iso6391: "te",
    },
    th: {
        key: "th",
        name: "Thai",
        flagCode: "🇹🇭",
        iso6391: "th",
    },
    tr: {
        key: "tr",
        name: "Turkish",
        flagCode: "🇹🇷",
        iso6391: "tr",
    },
    uk: {
        key: "uk",
        name: "Ukrainian",
        flagCode: "🇺🇦",
        iso6391: "uk",
    },
    ur: {
        key: "ur",
        name: "Urdu",
        flagCode: "🇵🇰",
        iso6391: "ur",
    },
    vi: {
        key: "vi",
        name: "Vietnamese",
        flagCode: "🇻🇳",
        iso6391: "vi",
    },
    "zh-Hans": {
        key: "zh-Hans",
        name: "Chinese (Simplified)",
        flagCode: "🇨🇳",
        iso6391: "zh",
        region: "Simplified",
    },
    "zh-Hant": {
        key: "zh-Hant",
        name: "Chinese (Traditional)",
        flagCode: "🇹🇼",
        iso6391: "zh",
        region: "Traditional",
    },
    zh: {
        key: "zh",
        name: "Chinese",
        flagCode: "🇨🇳",
        iso6391: "zh",
    },
};

export type LANGUAGE_KEY = (typeof LANGUAGE_MAP)[keyof typeof LANGUAGE_MAP];
